package entidades;
// Generated 26-09-2011 08:23:21 PM by Hibernate Tools 3.2.1.GA



/**
 * Asegurado generated by hbm2java
 */
public class Asegurado  implements java.io.Serializable {


     private Long idAsegurado;
     private HojaClinica hojaClinica;
     private long numSeguro;
     private String nombre;

    public Asegurado() {
    }

	
    public Asegurado(HojaClinica hojaClinica, long numSeguro) {
        this.hojaClinica = hojaClinica;
        this.numSeguro = numSeguro;
    }
    public Asegurado(HojaClinica hojaClinica, long numSeguro, String nombre) {
       this.hojaClinica = hojaClinica;
       this.numSeguro = numSeguro;
       this.nombre = nombre;
    
       
    }
   
    public Long getIdAsegurado() {
        return this.idAsegurado;
    }
    
    public void setIdAsegurado(Long idAsegurado) {
        this.idAsegurado = idAsegurado;
    }
    public HojaClinica getHojaClinica() {
        return this.hojaClinica;
    }
    
    public void setHojaClinica(HojaClinica hojaClinica) {
        this.hojaClinica = hojaClinica;
    }
    public long getNumSeguro() {
        return this.numSeguro;
    }
    
    public void setNumSeguro(long numSeguro) {
        this.numSeguro = numSeguro;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


