package entidades;
// Generated 14-10-2011 10:27:12 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Asegurado generated by hbm2java
 */
public class Asegurado  implements java.io.Serializable {


     private Long idAsegurado;
     private long numSeguro;
     private String nombre;
     private Set hojaClinicas = new HashSet(0);

    public Asegurado() {
    }

	
    public Asegurado(long numSeguro, String nombre) {
        this.numSeguro = numSeguro;
        this.nombre = nombre;
    }
    public Asegurado(long numSeguro, String nombre, Set hojaClinicas) {
       this.numSeguro = numSeguro;
       this.nombre = nombre;
       this.hojaClinicas = hojaClinicas;
    }
   
    public Long getIdAsegurado() {
        return this.idAsegurado;
    }
    
    public void setIdAsegurado(Long idAsegurado) {
        this.idAsegurado = idAsegurado;
    }
    public long getNumSeguro() {
        return this.numSeguro;
    }
    
    public void setNumSeguro(long numSeguro) {
        this.numSeguro = numSeguro;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getHojaClinicas() {
        return this.hojaClinicas;
    }
    
    public void setHojaClinicas(Set hojaClinicas) {
        this.hojaClinicas = hojaClinicas;
    }




}


