package entidades;
// Generated 14-10-2011 10:27:12 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Especialidad generated by hbm2java
 */
public class Especialidad  implements java.io.Serializable {


     private Integer idEspecialidad;
     private String nombre;
     private Set medicos = new HashSet(0);

    public Especialidad() {
    }

	
    public Especialidad(String nombre) {
        this.nombre = nombre;
    }
    public Especialidad(String nombre, Set medicos) {
       this.nombre = nombre;
       this.medicos = medicos;
    }
   
    public Integer getIdEspecialidad() {
        return this.idEspecialidad;
    }
    
    public void setIdEspecialidad(Integer idEspecialidad) {
        this.idEspecialidad = idEspecialidad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getMedicos() {
        return this.medicos;
    }
    
    public void setMedicos(Set medicos) {
        this.medicos = medicos;
    }




}


