package entidades;
// Generated 14-10-2011 10:27:12 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Habitacion generated by hbm2java
 */
public class Habitacion  implements java.io.Serializable {


     private Long idHabitacion;
     private Set hojaClinicas = new HashSet(0);

    public Habitacion() {
    }

    public Habitacion(Set hojaClinicas) {
       this.hojaClinicas = hojaClinicas;
    }
   
    public Long getIdHabitacion() {
        return this.idHabitacion;
    }
    
    public void setIdHabitacion(Long idHabitacion) {
        this.idHabitacion = idHabitacion;
    }
    public Set getHojaClinicas() {
        return this.hojaClinicas;
    }
    
    public void setHojaClinicas(Set hojaClinicas) {
        this.hojaClinicas = hojaClinicas;
    }




}


