package entidades;
// Generated 26-09-2011 08:23:21 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Habitacion generated by hbm2java
 */
public class Habitacion  implements java.io.Serializable {


     private Long idHabitacion;
     private Hospital hospital;
     private Set hojaClinicas = new HashSet(0);

    public Habitacion() {
    }

	
    public Habitacion(Hospital hospital) {
        this.hospital = hospital;
    }
    public Habitacion(Hospital hospital, Set hojaClinicas) {
       this.hospital = hospital;
       this.hojaClinicas = hojaClinicas;
    }
   
    public Long getIdHabitacion() {
        return this.idHabitacion;
    }
    
    public void setIdHabitacion(Long idHabitacion) {
        this.idHabitacion = idHabitacion;
    }
    public Hospital getHospital() {
        return this.hospital;
    }
    
    public void setHospital(Hospital hospital) {
        this.hospital = hospital;
    }
    public Set getHojaClinicas() {
        return this.hojaClinicas;
    }
    
    public void setHojaClinicas(Set hojaClinicas) {
        this.hojaClinicas = hojaClinicas;
    }




}


