package entidades;
// Generated 14-10-2011 10:27:12 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * HojaClinica generated by hbm2java
 */
public class HojaClinica  implements java.io.Serializable {


     private Long idHojaClinica;
     private Habitacion habitacion;
     private Medico medico;
     private Asegurado asegurado;
     private Integer num;
     private Date fechaIngreso;
     private String sintomas;
     private String diagnostico;
     private String tratamiento;
     private Boolean encamado;
     private Boolean alta;
     private Date fechaAlta;

    public HojaClinica() {
    }

	
    public HojaClinica(Asegurado asegurado, Date fechaIngreso, String sintomas) {
        this.asegurado = asegurado;
        this.fechaIngreso = fechaIngreso;
        this.sintomas = sintomas;
    }
    public HojaClinica(Habitacion habitacion, Medico medico, Asegurado asegurado, Integer num, Date fechaIngreso, String sintomas, String diagnostico, String tratamiento, Boolean encamado, Boolean alta, Date fechaAlta) {
       this.habitacion = habitacion;
       this.medico = medico;
       this.asegurado = asegurado;
       this.num = num;
       this.fechaIngreso = fechaIngreso;
       this.sintomas = sintomas;
       this.diagnostico = diagnostico;
       this.tratamiento = tratamiento;
       this.encamado = encamado;
       this.alta = alta;
       this.fechaAlta = fechaAlta;
    }
   
    public Long getIdHojaClinica() {
        return this.idHojaClinica;
    }
    
    public void setIdHojaClinica(Long idHojaClinica) {
        this.idHojaClinica = idHojaClinica;
    }
    public Habitacion getHabitacion() {
        return this.habitacion;
    }
    
    public void setHabitacion(Habitacion habitacion) {
        this.habitacion = habitacion;
    }
    public Medico getMedico() {
        return this.medico;
    }
    
    public void setMedico(Medico medico) {
        this.medico = medico;
    }
    public Asegurado getAsegurado() {
        return this.asegurado;
    }
    
    public void setAsegurado(Asegurado asegurado) {
        this.asegurado = asegurado;
    }
    public Integer getNum() {
        return this.num;
    }
    
    public void setNum(Integer num) {
        this.num = num;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public String getSintomas() {
        return this.sintomas;
    }
    
    public void setSintomas(String sintomas) {
        this.sintomas = sintomas;
    }
    public String getDiagnostico() {
        return this.diagnostico;
    }
    
    public void setDiagnostico(String diagnostico) {
        this.diagnostico = diagnostico;
    }
    public String getTratamiento() {
        return this.tratamiento;
    }
    
    public void setTratamiento(String tratamiento) {
        this.tratamiento = tratamiento;
    }
    public Boolean getEncamado() {
        return this.encamado;
    }
    
    public void setEncamado(Boolean encamado) {
        this.encamado = encamado;
    }
    public Boolean getAlta() {
        return this.alta;
    }
    
    public void setAlta(Boolean alta) {
        this.alta = alta;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }




}


