package entidades;
// Generated 26-09-2011 08:23:21 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Hospital generated by hbm2java
 */
public class Hospital  implements java.io.Serializable {


     private Long idHospital;
     private Set medicos = new HashSet(0);
     private Set habitacions = new HashSet(0);
     private Set hojaClinicas = new HashSet(0);

    public Hospital() {
    }

    public Hospital(Set medicos, Set habitacions, Set hojaClinicas) {
       this.medicos = medicos;
       this.habitacions = habitacions;
       this.hojaClinicas = hojaClinicas;
    }
   
    public Long getIdHospital() {
        return this.idHospital;
    }
    
    public void setIdHospital(Long idHospital) {
        this.idHospital = idHospital;
    }
    public Set getMedicos() {
        return this.medicos;
    }
    
    public void setMedicos(Set medicos) {
        this.medicos = medicos;
    }
    public Set getHabitacions() {
        return this.habitacions;
    }
    
    public void setHabitacions(Set habitacions) {
        this.habitacions = habitacions;
    }
    public Set getHojaClinicas() {
        return this.hojaClinicas;
    }
    
    public void setHojaClinicas(Set hojaClinicas) {
        this.hojaClinicas = hojaClinicas;
    }




}


