package entidades;
// Generated 26-09-2011 08:23:21 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Medico generated by hbm2java
 */
public class Medico  implements java.io.Serializable {


     private Long idMedico;
     private Hospital hospital;
     private int num;
     private String nombre;
     private Set hojaClinicas = new HashSet(0);

    public Medico() {
    }

	
    public Medico(Hospital hospital, int num) {
        this.hospital = hospital;
        this.num = num;
    }
    public Medico(Hospital hospital, int num, String nombre, Set hojaClinicas) {
       this.hospital = hospital;
       this.num = num;
       this.nombre = nombre;
       this.hojaClinicas = hojaClinicas;
    }
   
    public Long getIdMedico() {
        return this.idMedico;
    }
    
    public void setIdMedico(Long idMedico) {
        this.idMedico = idMedico;
    }
    public Hospital getHospital() {
        return this.hospital;
    }
    
    public void setHospital(Hospital hospital) {
        this.hospital = hospital;
    }
    public int getNum() {
        return this.num;
    }
    
    public void setNum(int num) {
        this.num = num;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getHojaClinicas() {
        return this.hojaClinicas;
    }
    
    public void setHojaClinicas(Set hojaClinicas) {
        this.hojaClinicas = hojaClinicas;
    }




}


