package entidades;
// Generated 14-10-2011 10:27:12 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Medico generated by hbm2java
 */
public class Medico  implements java.io.Serializable,Comparable {


     private Long idMedico;
     private Especialidad especialidad;
     private int num;
     private String nombre;
     private Set hojaClinicas = new HashSet(0);

    public Medico() {
    }

	
    public Medico(Especialidad especialidad, int num, String nombre) {
        this.especialidad = especialidad;
        this.num = num;
        this.nombre = nombre;
    }
    public Medico(Especialidad especialidad, int num, String nombre, Set hojaClinicas) {
       this.especialidad = especialidad;
       this.num = num;
       this.nombre = nombre;
       this.hojaClinicas = hojaClinicas;
    }
   
    public Long getIdMedico() {
        return this.idMedico;
    }
    
    public void setIdMedico(Long idMedico) {
        this.idMedico = idMedico;
    }
    public Especialidad getEspecialidad() {
        return this.especialidad;
    }
    
    public void setEspecialidad(Especialidad especialidad) {
        this.especialidad = especialidad;
    }
    public int getNum() {
        return this.num;
    }
    
    public void setNum(int num) {
        this.num = num;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getHojaClinicas() {
        return this.hojaClinicas;
    }
    
    public void setHojaClinicas(Set hojaClinicas) {
        this.hojaClinicas = hojaClinicas;
    }


	@Override
	public int compareTo(Object o) {
		Medico medicoComparable = (Medico)o;
		
		if(this.getHojaClinicas().size()>medicoComparable.getHojaClinicas().size()){
			return 1;
		}
		if(this.getHojaClinicas().size()<medicoComparable.getHojaClinicas().size()){
			return -1;
		}
		
		
		return 0;
	}




}


